---
version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
        environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
        ports: ['127.0.0.1:9200:9200']
        networks: ['stack']

    kibana:
        image: docker.elastic.co/kibana/kibana:6.1.1
        environment:
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=changeme
        ports: ['127.0.0.1:5601:5601']
        networks: ['stack']
        depends_on: ['elasticsearch']

networks:
    stack:
        driver: bridge
